//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grupo701D2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumnos
    {
        public long Matricula { get; set; }
        public string NombreC { get; set; }
        public string Telefono { get; set; }
        public string CorreoE { get; set; }
    }
}
