//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grupo701D2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class autobuses
    {
        public int Id { get; set; }
        public string Ruta { get; set; }
        public Nullable<double> Precio { get; set; }
        public string Marca { get; set; }
        public Nullable<short> TotalP { get; set; }
        public string Conductor { get; set; }
    }
}
